// import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
// import "../Styles/globals.css";
// import Header from "@/components/Header/Header";
// import Footer from "@/components/Footer/Footer";



// const museoModerno = MuseoModerno({
//   subsets: ["latin"],
//   variable: "--Font-MuseoModerno",
//   weight: ["300", "400" , "400" ,"600" , "700"],
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--Font-Poppins",
//   weight: ["300", "400" , "400" ,"600" , "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//       </head>
//       <body className={`${museoModerno.variable} ${poppins.variable}`}>
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import "../Styles/globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const space_Grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--Font-SpaceGrotesk",
  weight: ["300", "400", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${space_Grotesk.variable} font-gordita`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

