// import type { Metadata } from "next";
// import "../Styles/globals.css";
// import Header from "@/components/Header/Header";
// import Footer from "@/components/Footer/Footer";
// import { Space_Grotesk, Poppins } from "next/font/google"; // Ensure imports are at the top

// const space_Grotesk = Space_Grotesk({
//   subsets: ["latin"],
//   variable: "--Font-SpaceGrotesk",
//   weight: ["300", "400", "600", "700"],
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--Font-Poppins",
//   weight: ["300", "400", "600", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//       </head>
//       <body className={`${space_Grotesk.variable} ${poppins.variable} font-gordita`}>
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }

import "../Styles/globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Space_Grotesk, Poppins } from "next/font/google";
import ConditionalWrapper from "@/components/ConditionalWrapper"; // New client-side wrapper component
import { Providers } from "./redux/providers";
import Script from "next/script";
import Canonical from "./Canonical";

const space_Grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--Font-SpaceGrotesk",
  weight: ["300", "400", "600", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--Font-Poppins",
  weight: ["300", "400", "600", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="daUSUNFfgNz6HBE7DkYP6jsrgiCz3DDWT0mP696YPBA"
        />
        {/* code_221 */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Canonical />
      </head>
      <body
        className={`${space_Grotesk.variable} ${poppins.variable} font-gordita`}
      >
        <Providers>
          <ConditionalWrapper>{children}</ConditionalWrapper>
        </Providers>

        {/* <!-- Google tag (gtag.js) --> */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-6GPFSRTXQE"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
            gtag('config', 'G-6GPFSRTXQE');
            `,
          }}
        />
        {/* Google Tag Manager (GTM) */}
        <Script
        id="your-unique-id" 
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TGGL6B3L');`,
          }}
        />
        
      </body>
    </html>
  );
}
