name: Deploy Application

on:
  push:
    branches: [main]  # 'main' ब्रांच पर पुश होने पर वर्कफ़्लो शुरू होगा

jobs:
  deploy:
    runs-on: ubuntu-latest  # नवीनतम Ubuntu रनर का उपयोग करें

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # रिपॉजिटरी की सामग्री चेक आउट करें

      - name: Set up SSH key and server fingerprints
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "Current user: $(whoami)"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh  # .ssh डायरेक्टरी के लिए अनुमतियाँ

          # SSH कुंजी को सेट करें
          if [ -n "${{ secrets.SERVER_SSH_KEY_BASE64 }}" ]; then
            echo "${{ secrets.SERVER_SSH_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
          else
            echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          fi
          
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -t rsa $SERVER_IP >> ~/.ssh/known_hosts || { echo "ssh-keyscan failed"; exit 1; }
          chmod 644 ~/.ssh/known_hosts

      - name: Execute deployment commands
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -v -o BatchMode=yes -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP << 'EOF'
          set -e
          echo "Navigating to the project directory..."
          cd ~/labx/labx || { echo "Directory not found"; exit 1; }  # सही फ़ोल्डर में जाएँ

          echo "Pulling latest changes from Git repository..."
          git pull || { echo "Git pull failed"; exit 1; }

          echo "Installing project dependencies..."
          npm install || { echo "npm install failed"; exit 1; }

          echo "Building the project..."
          npm run build || { echo "Build failed"; exit 1; }

          echo "Restarting the application with PM2..."
          pm2 restart my-nextjs-app || { echo "Failed to restart the application"; exit 1; }

          echo "Deployment successful"
          EOF
