name: Deploy Next.js Application

on:
  push:
    branches: [ main ]  # This triggers the workflow on push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up SSH key and server fingerprints
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Execute deployment commands
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/ec2-user/labx
          git pull
          npm install
          npm run build
          # Restart your application, depends on your process manager, here's an example using PM2
          pm2 restart all
          EOF
