name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "Setting up SSH environment..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Install NVM and Node.js
        run: |
          echo "Installing NVM..."
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18

      - name: Prepare deployment script
        run: |
          echo 'echo "Starting Deployment..."' > deploy_script.sh
          echo 'export NVM_DIR="$HOME/.nvm"' >> deploy_script.sh
          echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"' >> deploy_script.sh
          echo 'nvm use 18' >> deploy_script.sh
          echo 'cd /home/ec2-user/labx || exit 1' >> deploy_script.sh
          echo 'git config --global --add safe.directory /home/ec2-user/labx' >> deploy_script.sh
          echo 'git stash push --include-untracked || echo "No changes to stash"' >> deploy_script.sh
          echo 'git pull origin main' >> deploy_script.sh
          echo 'npm install --legacy-peer-deps' >> deploy_script.sh
          echo 'NODE_OPTIONS="--max-old-space-size=2048" npm run build' >> deploy_script.sh
          echo 'sudo npm install -g pm2' >> deploy_script.sh
          echo 'pm2 delete all || true' >> deploy_script.sh
          echo 'pm2 start ecosystem.config.js --env production' >> deploy_script.sh
          echo 'pm2 save' >> deploy_script.sh
          echo 'echo "Deployment completed successfully."' >> deploy_script.sh
          chmod +x deploy_script.sh

      - name: Transfer and execute deployment script
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Transferring and executing deployment script..."
          scp -o StrictHostKeyChecking=no deploy_script.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/tmp/
          ssh -T -o BatchMode=yes -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "bash /tmp/deploy_script.sh"

      - name: Debug SSH connection (if failed)
        if: failure()
        run: |
          echo "Debugging SSH connection..."
          ssh -vvv -T -o BatchMode=yes -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} exit

      - name: Post-deployment success confirmation
        if: success()
        run: echo "Deployment successful! All steps completed without errors."

      - name: Check server status
        if: success()
        run: |
          echo "Checking server status..."
          ssh -T -o BatchMode=yes -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "pm2 status"
