name: Node.js CI/CD Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Navigating to the project directory..."
            cd ~/labx || exit 1
            
            echo "Checking directory contents and permissions..."
            ls -la  # List files and their permissions

            echo "Verifying if it's a Git repository..."
            git status || (echo "Directory is not a git repository; cloning..." && git clone https://github.com/SaurabhBhatiaodesk/labx.git .)
            
            echo "Pulling latest changes from the repository..."
            git pull || exit 1

            echo "Installing dependencies..."
            npm install || (echo "Failed to install dependencies; exiting..." && exit 1)

            echo "Building the project..."
            npm run build || (echo "Build failed; exiting..." && exit 1)

            echo "Restarting the application with PM2..."
            pm2 restart all || (echo "Failed to restart the application; exiting..." && exit 1)

            echo "Deployment successful."
